### ISSUE TITLE
執行train_net.py遇到的問題

### ISSUE THREAD

**Issue by Ting0887** [ricky-696/AICUP_Baseline_BoT-SORT#10]
執行train_net.py遇到的問題

**Comment by Ting0887** [comment]
Traceback (most recent call last):   File "/content/drive/MyDrive/AICup_MCMOT_Baseline/fast_reid/tools/train_net.py", line 13, in <module>     from fast_reid.fastreid.config import get_cfg   File "/content/drive/MyDrive/AICup_MCMOT_Baseline/fast_reid/fastreid/config/__init__.py", line 7, in <module>     from .config import CfgNode, get_cfg, global_cfg, set_global_cfg, configurable   File "/content/drive/MyDrive/AICup_MCMOT_Baseline/fast_reid/fastreid/config/config.py", line 15, in <module>     from yacs.config import CfgNode as _CfgNode ModuleNotFoundError: No module named 'yacs'

**Comment by ricky-696** [comment]
上面寫找不到`yacs`這個套件，這套件我有包在[requirements.txt](https://github.com/ricky-696/AICUP_Baseline_BoT-SORT/blob/main/requirements.txt)內，請確實把[Installation](https://github.com/ricky-696/AICUP_Baseline_BoT-SORT?tab=readme-ov-file#installation)的步驟做好!!

**Comment by Ting0887** [comment]
嗨，你好，我確認有安裝這個套件，但onnxruntime這個套件似乎安裝失敗
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from -r /content/drive/MyDrive/AICup_MCMOT_Baseline/requirements.txt (line 1)) (1.25.2)
Requirement already satisfied: opencv-python in /usr/local/lib/python3.10/dist-packages (from -r /content/drive/MyDrive/AICup_MCMOT_Baseline/requirements.txt (line 2)) (4.8.0.76)
Collecting loguru (from -r /content/drive/MyDrive/AICup_MCMOT_Baseline/requirements.txt (line 3))
  Using cached loguru-0.7.2-py3-none-any.whl (62 kB)
Requirement already satisfied: scikit-image in /usr/local/lib/python3.10/dist-packages (from -r /content/drive/MyDrive/AICup_MCMOT_Baseline/requirements.txt (line 4)) (0.19.3)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (from -r /content/drive/MyDrive/AICup_MCMOT_Baseline/requirements.txt (line 5)) (1.2.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from -r /content/drive/MyDrive/AICup_MCMOT_Baseline/requirements.txt (line 6)) (4.66.4)
Requirement already satisfied: torchvision>=0.10.0 in /usr/local/lib/python3.10/dist-packages (from -r /content/drive/MyDrive/AICup_MCMOT_Baseline/requirements.txt (line 7)) (0.17.1+cu121)
Requirement already satisfied: Pillow in /usr/local/lib/python3.10/dist-packages (from -r /content/drive/MyDrive/AICup_MCMOT_Baseline/requirements.txt (line 8)) (9.4.0)
Collecting thop (from -r /content/drive/MyDrive/AICup_MCMOT_Baseline/requirements.txt (line 9))
  Using cached thop-0.1.1.post2209072238-py3-none-any.whl (15 kB)
Collecting ninja (from -r /content/drive/MyDrive/AICup_MCMOT_Baseline/requirements.txt (line 10))
  Using cached ninja-1.11.1.1-py2.py3-none-manylinux1_x86_64.manylinux_2_5_x86_64.whl (307 kB)
Requirement already satisfied: tabulate in /usr/local/lib/python3.10/dist-packages (from -r /content/drive/MyDrive/AICup_MCMOT_Baseline/requirements.txt (line 11)) (0.9.0)
Requirement already satisfied: tensorboard in /usr/local/lib/python3.10/dist-packages (from -r /content/drive/MyDrive/AICup_MCMOT_Baseline/requirements.txt (line 12)) (2.15.2)
Collecting lap (from -r /content/drive/MyDrive/AICup_MCMOT_Baseline/requirements.txt (line 13))
  Using cached lap-0.4.0-cp310-cp310-linux_x86_64.whl
Collecting filterpy (from -r /content/drive/MyDrive/AICup_MCMOT_Baseline/requirements.txt (line 14))
  Using cached filterpy-1.4.5-py3-none-any.whl
Requirement already satisfied: h5py in /usr/local/lib/python3.10/dist-packages (from -r /content/drive/MyDrive/AICup_MCMOT_Baseline/requirements.txt (line 15)) (3.9.0)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (from -r /content/drive/MyDrive/AICup_MCMOT_Baseline/requirements.txt (line 16)) (3.7.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from -r /content/drive/MyDrive/AICup_MCMOT_Baseline/requirements.txt (line 17)) (1.11.4)
Requirement already satisfied: seaborn in /usr/local/lib/python3.10/dist-packages (from -r /content/drive/MyDrive/AICup_MCMOT_Baseline/requirements.txt (line 18)) (0.13.1)
Requirement already satisfied: prettytable in /usr/local/lib/python3.10/dist-packages (from -r /content/drive/MyDrive/AICup_MCMOT_Baseline/requirements.txt (line 19)) (3.10.0)
Requirement already satisfied: easydict in /usr/local/lib/python3.10/dist-packages (from -r /content/drive/MyDrive/AICup_MCMOT_Baseline/requirements.txt (line 20)) (1.13)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.10/dist-packages (from -r /content/drive/MyDrive/AICup_MCMOT_Baseline/requirements.txt (line 22)) (6.0.1)
Collecting yacs (from -r /content/drive/MyDrive/AICup_MCMOT_Baseline/requirements.txt (line 23))
  Using cached yacs-0.1.8-py3-none-any.whl (14 kB)
Requirement already satisfied: termcolor in /usr/local/lib/python3.10/dist-packages (from -r /content/drive/MyDrive/AICup_MCMOT_Baseline/requirements.txt (line 24)) (2.4.0)
Requirement already satisfied: gdown in /usr/local/lib/python3.10/dist-packages (from -r /content/drive/MyDrive/AICup_MCMOT_Baseline/requirements.txt (line 25)) (5.1.0)
Collecting onnx==1.8.1 (from -r /content/drive/MyDrive/AICup_MCMOT_Baseline/requirements.txt (line 26))
  Using cached onnx-1.8.1.tar.gz (5.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
ERROR: Could not find a version that satisfies the requirement onnxruntime==1.8.0 (from versions: 1.12.0, 1.12.1, 1.13.1, 1.14.0, 1.14.1, 1.15.0, 1.15.1, 1.16.0, 1.16.1, 1.16.2, 1.16.3, 1.17.0, 1.17.1, 1.17.3)
ERROR: No matching distribution found for onnxruntime==1.8.0

**Comment by ricky-696** [comment]
第一，你的Python版本並沒有照Readme上面的版本安裝，遊戲規則就放在那邊，你不照做然後一直來貼Issue，不知道什麼意思。
第二，請善用網路資源，把最後一行的error貼到google上馬上就找到[解決方法](https://github.com/ifzhang/ByteTrack/issues/349)了
我不是ChatGPT，也不是Google，環境問題除非100%確定是我這邊造成的Issue，不然不要來吵我，不然你乾脆叫我幫你比好了

**Comment by Ting0887** [comment]
我很抱歉打擾你了，感謝你的說明~~~
因為這個問題，我在colab執行的時候遇到，
剛剛我又確認了一下colab的python版本，結果是3.10，
那這個應該就是問題了，我在自己想想看。
