### ISSUE TITLE
關於Training (Fine-tuning)問題

### ISSUE THREAD

**Issue by Sinze0531** [ricky-696/AICUP_Baseline_BoT-SORT#12]
您好，想詢問一下Train the ReID Module for AICUP中"The training results are stored by default in logs/AICUP/bagtricks_R50-ibn"的logs資料夾從哪裡取得? 謝謝!!

**Comment by ricky-696** [comment]
你執行的路徑在哪裡，他就會在執行的路徑產生一個logs資料夾。
如果你在`Project/AICUP_Baseline_BoT-SORT`執行程式，
程式碼會自己幫你產生`Project/AICUP_Baseline_BoT-SORT/logs/AICUP_115/bagtricks_R50-ibn`資料夾。
