### ISSUE TITLE
關於競賽 submission 格式相關問題

### ISSUE THREAD

**Issue by b06b01073** [ricky-696/AICUP_Baseline_BoT-SORT#19]
您好，根據 [tbrain官網](https://tbrain.trendmicro.com.tw/Competitions/Details/33) 的說明
> 參照「32_33_submission_sample.zip」格式，將多個text檔案(*.txt)放在一個資料夾當中，將此資料夾壓縮成zip檔案(*.zip)後上傳

最後 submission 的 zip 檔開啟後應該會看到含有所有 txt 檔的資料夾。而官方給的 32_33_submission_sample.zip 點進去則已經是所有的 txt 檔，而並沒有看到 **將多個text檔案(*.txt)放在一個資料夾當中** 所提到的資料夾，想要請問官網對於 submission 格式的說明是否有誤? 謝謝。

**Comment by Hsinsin** [comment]
您好，目前已經將此問題提交給 tbrain ，因為目前已經是下班時間，明日開放繳交前應會有相關補充說明於官網共告處，請隨時注意相關訊息。

若沒有補充公告，我們的預設格式與文字說明相同，應將 text 檔案以資料夾包起來再進行壓縮後繳交，其餘相關規定以官網為主。

**Comment by Hsinsin** [comment]
您好，補充官方提供的說明如下：

參賽者可以自己命名，只要是一個zip檔案中包含所有需要評分的txt就可以。
submission sample只是sample，提供參考而已，不需要照著這個名稱的。
不論Zip裡是否還有一層文件夾，評分系統都可以讀取評分。
