### ISSUE TITLE
tools/mc_demo_yolov7.py  無法找到yolov7.models  已經install yolov7過了    #已解決  

### ISSUE THREAD

**Issue by yhy930404** [ricky-696/AICUP_Baseline_BoT-SORT#22]
python tools/mc_demo_yolov7.py --weights runs\train\yolov7-AICUP\weights\best.pt --source 32_33_AI_CUP_testdataset\32_33_AI_CUP_testdataset\AI_CUP_testdata\images\0902_130006_131041 --device "0" --name "0902_130006_131041" --fuse-score --agnostic-nms --with-reid --fast-reid-config fast_reid\configs\AICUP\bagtricks_R50-ibn.yml --fast-reid-weights logs\AICUP_115\bagtricks_R50-ibn\model_0058.pth
![image](https://github.com/ricky-696/AICUP_Baseline_BoT-SORT/assets/79523816/991897a3-621c-4781-b078-c4631556cc1a)

**Comment by ricky-696** [comment]
1. 我們使用的yolov7 model的路徑在[這邊](https://github.com/ricky-696/AICUP_Baseline_BoT-SORT/tree/main/yolov7)，不需要額外install yolov7
2. 會出現上面的問題通常都是路徑設定錯誤，所以他找不到yolov7這個資料夾，我看你是用Windows，可能在下面的地方需要更改一下環境變數的設定，譬如`os.getcwd()`之類的。
https://github.com/ricky-696/AICUP_Baseline_BoT-SORT/blob/0d5b81486556068f5ee7e845ee6d511cbc87ee43/tools/mc_demo_yolov7.py#L13-L14

P.S: 如果問題已經解決可以直接Close Issue，不需要在標題上面Hashtag這樣

**Comment by yhy930404** [comment]
感謝 已解決!!
