### ISSUE TITLE
fast reid evaluation 問題

### ISSUE THREAD

**Issue by MuennL** [ricky-696/AICUP_Baseline_BoT-SORT#4]
主辦老師們好:

我們這隊希望評估fast_reid在此競賽之custom dataset的效能。
此競賽之read_me的tutorial中尚未明確指明如何建立query資料，照fast_reid之documentation來看資料應該要符合market 1501之命名規範，不過AICUP的命名邏輯似乎不同。
請問主辦單位是否能提供建立fast_reid evaluation資料的相關指引?

**Comment by ricky-696** [comment]
沒辦法，謝謝
