### ISSUE TITLE
關於yolo的問題

### ISSUE THREAD

**Issue by Arbeliwus** [ricky-696/AICUP_Baseline_BoT-SORT#5]
想詢問關於datasets/AI_CUP_MCMOT_dataset/yolo的資料是從那裡取得

**Comment by blackline0911** [comment]
那個要在跟train相同的資料夾中自己另外新增一個資料夾叫yolo

**Comment by ricky-696** [comment]
哈囉~
關於如何產生Yolo的訓練資料請看[這邊](https://github.com/ricky-696/AICUP_Baseline_BoT-SORT?tab=readme-ov-file#prepare-yolov7-dataset)

與@blackline0911 回答的一樣，在`--YOLOv7_dir` 這個參數中指定你要產生資料的位置，`AICUP_to_YOLOv7.py`會自動幫你建立資料夾，並把訓練資料產生到那邊
